spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: ashokit
    password: ashokit
    driverClassName: org.h2.Driver

plan-api:
    messages:
        planSaveSucc: Plan Saved Successfully
        planSaveFail: Plan Save Failed
        planUpdateSucc: Plan Updated Successfully
        planUpdateFail: Plan Update Failed
        planDeleteSucc: Plan  Deleted Successfully
        planDeleteFail: Plan Delete Failed
        planStatusChangeSucc: Plan Status Changed Successfully
        planStatusChangeFail: Plan Status Change Failed